spring.config.import=optional:file:.env

#DB 설정
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Redis 설정
spring.redis.host=192.168.0.141
spring.redis.port=6379

# Kafka Producer 설정
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Kafka 설정
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9094}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka Topic
app.kafka.topic.festival-event=festival-topic

# API Key
festival.api.key=${FESTIVAL_API_KEY:dummy-key}

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.default-produces-media-type=application/json
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.override-with-generic-response=false

# Kakao
kakao.restapi-key=${KAKAO_REST_API_KEY}
kakao.search-base-url=https://dapi.kakao.com

#10s
festival.geocode.initial-delay-ms=10000
#60m
festival.geocode.fixed-delay-ms=3600000

# Server Port
server.port=8083

#AI URL
ai.url=${AI_URL}

# S3
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.sts.role-arn=${AWS_STS_ROLE_ARN}

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.probes.enabled=true

app.base-url=${APP_BASE_URL:http://localhost:10000}

