# Spring Application Name & Profile
spring.application.name=festival-service
spring.profiles.active=test

# MariaDB 설정
spring.datasource.url=jdbc:mariadb://192.168.0.139:3306/festival
spring.datasource.username=festivaluser
spring.datasource.password=festivalpw
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Redis 설정
spring.redis.host=192.168.0.139
spring.redis.port=6379

# Kafka 설정
spring.kafka.bootstrap-servers=192.168.0.139:9094

# Kafka Producer 설정
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Kafka Topic 명 관리 (Custom Property)
app.kafka.topic.festival-event=festival-event

# Server Port (테스트 서버 포트)
server.port=9090
