spring.application.name=festival-service
spring.batch.job.enabled=true

# 프로필 분리
spring.profiles.active=test

# 환경변수 import (.env 파일)
spring.config.import=optional:file:.env[.properties]

# festival-api-key는 profile 별로 application-*.properties 에서 설정
festival.api.key=${FESTIVAL_API_KEY:dummy-key}

app.kafka.topic.festival-event=festival-topic